Add links to talks at 36C3 and FOSDEM
emissions-api/emissions-api.github.com pull request #33
Opened 2020-02-05 21:06 UTC by tibroc

This patch adds the links to the lightning talks held at 36C3 and
FOSDEM 2020 to the home page.

2020-02-06 16:26 UTC, shaardie requested changes
Maybe a anti chronologically order would be better?!

2020-02-07 08:16 UTC, TylerBird commented
I also would suggest to rethink the order of the links. I hope that is what @shaardie meant. Also starting with upper-case letter.

2020-02-10 22:13 UTC, lkiesow commented
And we usually capitalize the first character of list items

2020-02-11 20:20 UTC, tibroc commented
@TylerBird @lkiesow I changed the first letter of each point to capital

@shaardie while I first also leaned towards an anti-chronological order. I found this order was the most useful for somebody visiting our page: a short introduction (the 26c3 talk), then a longer introduction and, finally, the podcast if you are really interested.

2020-02-11 20:54 UTC, lkiesow commented
Fine with me. Merged.

2020-02-11 20:54 UTC, merged