Carbon Monoxide Highscore of Cities
emissions-api/emissions-api.github.com pull request #43
Opened 2020-02-16 23:55 UTC by lkiesow

This patch adds a new guide, explaining how to build a carbon monoxide
highscore board for cities.

2020-02-17 21:55 UTC, shaardie requested changes
Just some minor suggestions and flaws.

I am missing some kind of outlook or clean ending for the example. It stops pretty sudden.

2020-02-17 21:55 UTC, shaardie commented on examples/highscore.md
> +This is the finished highscore for a few cities on Feb 01, 2020, listing them in descending order (city with least carbon monoxide first)
I think your data is from 2019
```suggestion
This is the finished highscore for a few cities on Feb 01, 2019, listing them in descending order (city with least carbon monoxide first)
```

2020-02-17 21:55 UTC, shaardie commented on examples/highscore.md
> +Additionally, this code lacks any error handling so that, for example, the non-existence of data in one city for the
I would not go into detail here.

```suggestion
Additionally, this code lacks any error handling.
```

2020-02-17 21:55 UTC, shaardie commented on examples/highscore.md
> +requested day may cause the whole code to fail.
```suggestion
```

2020-02-17 21:55 UTC, shaardie commented on examples/highscore.md
> +Now that we got all the data we need, we just need to sort the data according to the carbon monoxide data
```suggestion
Now that we got all the data we need, we just need to sort the them according to the carbon monoxide
```

2020-02-17 21:55 UTC, shaardie commented on examples/highscore.md
> +```
Very functional :+1:

2020-02-20 12:43 UTC, EmbeddedHenni commented
lgtm
works pretty well for me.
no issues during testing.
with @shaardie 's permission i'm going to merge this request.

2020-02-20 12:44 UTC, merged